AppointmentBookingSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('appointments/', include('appointments.urls') ),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from accounts.views import AddDoctorView, DoctorProfileView, UpdateDoctorView, ChangeDoctorPasswordView, UpdatePatientView

urlpatterns = [
    path("add_doctor/", AddDoctorView.as_view(), name="add_doctor"),
    path('profile/<pk>/', DoctorProfileView.as_view(), name='profile'),
    path('update/<pk>/', UpdateDoctorView.as_view(), name='update'),
    path('profile/update/<pk>/', UpdatePatientView.as_view(), name='update_profile'),
    path('change_password/', ChangeDoctorPasswordView.as_view(), name='change_password'),

] 

appointments/urls.py
from django.urls import path
from .views import SpecialitiesView, BookAppointment, AppointmentListView, AppointmentDetailView, RescheduleView
from . import views
urlpatterns = [
    path('specialities/', SpecialitiesView.as_view(), name="specialities" ),
    path('booking/', BookAppointment.as_view(), name="booking"),
    path('appointment_list/', AppointmentListView.as_view(), name="appointment_list"),
    path('load_doc/', views.load_doc, name="load_doc" ),
    path('<pk>/', AppointmentDetailView.as_view(), name="appointment"),
    path('accept/<int:pk>/', views.appointment_accept, name="appointment_cancel"),
    path('accept/<int:pk>/<str:action>/', views.appointment_accept, name="appointment_cancel"),
    path('reschedule/<pk>', RescheduleView.as_view(), name="reschedule"),
] 

appointments/models.py
from django.db import models
from accounts.models import User
from django.urls import reverse
from appointments.constants import STATUS

# Create your models here.


class Appointment(models.Model):
    patient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='patient')
    doctor = models.ForeignKey(User, on_delete=models.CASCADE,  related_name='doctor')
    appoint_date = models.DateTimeField(null=True, blank=True)
    update_date = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=50, choices=STATUS, null=True, blank=True, default=STATUS[0][0])
    description = models.TextField(null=True, blank=True)

    def get_absolute_url(self):
        return reverse('appointment', kwargs={'pk': self.id})

appointments/forms.py
from accounts.models import User, Speciality
from appointments.models import Appointment
from django import forms
from accounts.constants import ROLE, SPECIALITIES
import datetime


class AppointmentForm(forms.ModelForm):
    """ This form for create appointment ."""
    specialities = forms.ModelChoiceField(queryset=Speciality.objects.all(),
                                    to_field_name = 'name',
                                    empty_label="Select Speciality")

    class Meta:
        model = Appointment
        fields = ('specialities', 'doctor', 'appoint_date', 'description')
        widgets = {
            'appoint_date': forms.DateTimeInput(
                attrs={'type': 'datetime-local', 'class': 'datetimepicker', 'min': 'datetime.datetime.today()'}),
        }

    def __init__(self, *args, **kwargs):
        super(AppointmentForm, self).__init__(*args, **kwargs)
        self.fields['doctor'].queryset = User.objects.filter(role__name=ROLE[0][0])
        if 'specialities' in self.data:
            breakpoint()
            spec = self.data.get('specialities')
            speciality = Speciality.objects.get(name=spec)
            doc = User.objects.filter(role__name=ROLE[0][0])
            self.fields['doctor'].queryset = doc.filter(specialities=speciality)


class RescheduleForm(forms.ModelForm):
    """ This form for reschedule appointment by doctor."""
    class Meta:
        model = Appointment
        fields = ('appoint_date', 'description')
        widgets = {
            'appoint_date': forms.DateTimeInput(
                attrs={'type': 'datetime-local', 'class': 'datetimepicker', 'min': 'datetime.datetime.today()'}),
        }

appointments/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import View
from django.views.generic import ListView, UpdateView
from django.views.generic.detail import DetailView
from accounts.constants import ROLE
from accounts.models import User
from django.db.models import Count
from appointments.forms import AppointmentForm, RescheduleForm
from appointments.models import STATUS, Appointment
from django.core.mail import send_mail
from AppointmentBookingSystem.settings import EMAIL_HOST_USER


# Create your views here.


class SpecialitiesView(LoginRequiredMixin, View):
    """for specialities of doctors"""

    def get(self, request):
        doctors = User.objects.filter(role__name=ROLE[0][0])
        specialities = User.objects.exclude(specialities=None).values('specialities__name').annotate(Count('specialities'))
        data = {"specialities": specialities, "doctors": doctors}
        return render(request, "specialities.html", data)


class BookAppointment(LoginRequiredMixin, View):
    """ for create appointment"""

    def get(self, request):
        user = request.GET.get('doctor_id')
        if user:
            spec = User.objects.get(id=user)
            form = AppointmentForm(initial={'specialities': spec.specialities.name, 'doctor': user})
        else:
            form = AppointmentForm()

        return render(request, 'account/_application_form.html', {'form': form})

    def post(self, request):
        form = AppointmentForm(request.POST)
        if form.is_valid():
            appointment_data = form.save(commit=False)
            appointment_data.patient = self.request.user
            appointment_data.save()
            subject = "New Appointment..."
            message = "Hello {doctor} \nappointmentt for checkup....\nappointment date :{date} \n description : {desc} ".format(
                doctor=appointment_data.doctor, date=appointment_data.appoint_date,
                desc="http://127.0.0.1:8000/appointments/{p}/".format(p=appointment_data.id))
            send_mail(subject, message, EMAIL_HOST_USER, [appointment_data.doctor.email], fail_silently=False, )
            return redirect('index')
        else:
            form = AppointmentForm()
            return render(request, 'account/_application_form.html', {'form': form})


def load_doc(request):
    breakpoint()
    spec = request.GET.get('sepc')
    doc = User.objects.filter(specialities=spec)
    return render(request, 'account/_doc_list.html', {'doc_list': doc})


class AppointmentListView(LoginRequiredMixin, ListView):
    """ for appointment list of doctor"""
    model = Appointment
    template_name = "appointment_list.html"
    context_object_name = "appoint_list"

    def get_queryset(self):
        query = Appointment.objects.filter(doctor=self.request.user)
        # for filter and search functionaties
        # filter = self.request.GET.get('filter')
        # search = self.request.GET.get('search', '')
        # if search:
        #     query =  query.filter(patient__username__icontains = search )
        # if filter:
        #     query =  query.filter(status = filter)
        # for datetime gone then save completed
        # for q in query:
        #     if q.appoint_date.date() < datetime.date.today():
        #         q.status = STATUS[2][1]
        #         q.save()
        #     else:
        #         q.status = STATUS[0][0]
        #         q.save()
        return query

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_option'] = Appointment.objects.filter(doctor=self.request.user).values('status').distinct()
        context['filter'] = self.request.GET.get('filter')
        context['search'] = self.request.GET.get('search')
        return context


class AppointmentDetailView(LoginRequiredMixin, DetailView):
    """ detail view of appointment to check"""
    model = Appointment
    template_name = "appointment.html"
    context_object_name = "appointments"


def appointment_accept(request, pk, action):
    appointment = Appointment.objects.filter(id=pk)
    if action == "Accept":
        appointment.update(status=STATUS[1][0])
        return redirect('appointment_list')
    elif action == "Cancel":
        appointment.update(status=STATUS[4][0])
        return redirect('appointment_list')
    appointments = appointment.first()
    return render(request, 'appointment.html', {'appointments': appointments})


class RescheduleView(LoginRequiredMixin, View):
    def get(self, request, pk):
        appointment = Appointment.objects.filter(id=pk).first()
        form = AppointmentForm(instance=appointment)
        form.fields['doctor'].disabled = form.fields['specialities'].disabled = form.fields[
            'specialities'].disabled = True
        return render(request, '_reschedule_form.html', {'form': form})

    def post(self, request, pk):
        appointment_obj = Appointment.objects.filter(id=pk).first()
        form = RescheduleForm(request.POST, instance=appointment_obj)
        if form.is_valid():
            appointment_data = form.save(commit=False)
            appointment_data.save()
            appointment = Appointment.objects.filter(id=pk)
            appointment.update(status=STATUS[3][0])
            return redirect('appointment_list')

templates/_reschedule_form.html
{% extends "index.html" %}
{% load i18n %}
{% block head_title %}{% trans "Update Profile" %}{% endblock %}
{% block content%}
<section class="contact-section">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="contact-title">Reschedule Appointment </h2>
            </div>
            <div class="col-lg-8">
                <form action="" method="post" id="updateform">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" class="btn btn-primary" value="Submit &raquo;">
                </form>
            </div>
        </div>                                 
    </div>
</section>
<script>
$(document).ready(function (){
    var d = new Date();
    var fullDate=d.getFullYear() + "-" + (d.getMonth()+1) + "-" + d.getDate() + "T00:00";
    console.log(fullDate);
    $('.datetimepicker').attr(
        {'min': fullDate }
    );
});
</script>
{% endblock %}

templates/about.html
    <!-- quality_area_start  -->
    <div class="quality_area">
        <div class="container">
            <div class="row justify-content-center ">
                <div class="col-lg-6">
                    <div class="section_title mb-55 text-center">
                        <h3>Quality Health</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <div class="single_quality">
                        <div class="icon">
                            <i class="flaticon-customer-service"></i>
                        </div>
                        <h3>Health Consultation</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="single_quality">
                        <div class="icon">
                            <i class="flaticon-find"></i>
                        </div>
                        <h3>Find Health</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="single_quality">
                        <div class="icon">
                            <i class="flaticon-doctor"></i>
                        </div>
                        <h3>Search Deoctor</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- quality_areaend  -->

templates/appointment_list.html
{% extends 'index.html' %}
{% load static   %}
{% block content %}
<div class="depertment_area">
    <div class="container">
<div class="whole-wrap">
    <div class="container box_1170">
        <div class="section-top-border">
            <div class="row">
                <div class="col-lg-8 col-md-8">
                    <h3 class="mb-30">Appointment List</h3>
                    <div class="progress-table-wrap">
                        <table id="table_id" class="display">
                            <thead>
                                <tr>
                                    <th>Patient Name</th>
                                    <th>Date</th>
                                    <th>Time</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for list in appoint_list %}
                                <tr>
                                    <td ><a href="{% url 'appointment' list.id %}">{{list.patient}}</a></td>
                                    <td>{{list.appoint_date|date}}</td>
                                    <td>{{list.appoint_date|time}}</td>
                                    <td>{{list.get_status_display}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        
                    </div>
                   
                </div>
                
                <div class="col-lg-4">
                    <div class="blog_right_sidebar">
                        <aside class="single_sidebar_widget newsletter_widget">
                            <div class="single-element-widget mt-30">
                                <h3 class="mb-20">Filter</h3>
                                <div class="default-select" id="default-select">
                                    <select name="filter_status" id="filter_status" onchange="Data();">
                                        <option value="" >---</option>
                                        {% for f in filter_option %}
                                            {% comment %} <option value="{{f.status}}" {% if filter == f.status %}selected  {% else %}{% endif %} >{{f.status}}</option> {% endcomment %}
                                            <option value="{{f.status}}">{{f.status}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div> 
                        </aside>
                        {% comment %} <aside class="single_sidebar_widget search_widget">
                
                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" name='search' {% if search %} value='{{search}}' {% else %}  {% endif %}placeholder="Search"  onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search patient'" id="search">
                                    </div>
                                </div>
                        </aside> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    const Data=()=>{
        var table = $('#table_id').DataTable();
        table.column(3).search($("#filter_status").val());
        table.column(3).draw();
    }
    $(document).ready( function () {
        $('#table_id').DataTable();
        $(".dataTables_length").hide();
    } );

   
</script>
{% comment %} <script>
    $(document).ready(function (){
        $('#filter_status , #search').change(function() {
            var id = $('#filter_status').val();
            var search = $('#search').val();
            $.get("{% url 'appointment_list' %}", {'filter' : id, 'search': search } , function (data) {
                window.location.replace("http://127.0.0.1:8000/appointments/appointment_list/?filter="+id + "&search="+search );
            });
        });
    });
</script> {% endcomment %}
{% endblock %}

templates/index.html
{% load static%}
{% load i18n %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Medi</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
</head>

<body>
    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-xl-3 col-lg-3">
                            <div class="logo-img">
                                <a href="{% url 'index'%}">
                                    <img src="{% static 'img/logo.png' %}" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-9 col-lg-9">
                            <div class="menu_wrap d-none d-lg-block">
                                <div class="menu_wrap_inner d-flex align-items-center justify-content-end">
                                    <div class="main-menu">
                                        <nav>
                                            <ul id="navigation">
                                                <li><a href="{% url 'index'%}">home</a></li>
                                                <li><a href="">About</a></li>
                                                <li><a href="#">Departments <i class="ti-angle-down"></i></a>
                                                    <ul class="submenu">
                                                        {% if user.is_superuser %}
                                                        <li><a href="{% url 'add_doctor'%}">Add Doctor</a></li>
                                                        {% endif %}
                                                        <li><a href="{% url 'specialities'%}">Specialities</a></li>
                                                        <li><a href="">Manage Section </a></li>
                                                    </ul>
                                                </li>
                                                {% if user.is_superuser %}

                                                {% elif user.is_staff %}
                                                <li><a href="#">Appointments <i class="ti-angle-down"></i></a>
                                                    <ul class="submenu">   
                                                        <li><a href="{% url 'appointment_list'%}">lists</a></li>                                                       
                                                    </ul>
                                                </li>
                                                {% endif %}
                                                {% if user.is_authenticated %}
                                                <li><a href="#">account <i class="ti-angle-down"></i></a>
                                                    <ul class="submenu">
                                                    <li><a href="{% url 'profile' user.id%}">Profile</a></li>
                                                    <li><a href="{% url 'change_password' %}">Change Password</a></li>
                                                    <li><a href="{% url 'account_logout' %}">Sign Out</a></li>
                                                    </ul>
                                                {% else %}
                                                    <li><a href="{% url 'account_login' %}">Sign In</a></li>
                                                {% endif %}
                                                </li>
                                            </ul>
                                        </nav>
                                    </div>
                                    <div class="book_room">
                                        <div class="book_btn">
                                            
                                        </div>
                                       
                                    </div>
                                </div>
                            </div>
                        </div>
    
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->

    {% block content %}
    <!-- slider_area_start -->
        <div class="slider_area">
            <div class="slider_active owl-carousel">
                <div class="single_slider  d-flex align-items-center slider_bg_1 overlay">
                    <div class="container">
                        {% for message in messages %}
                            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                {{ message }}
                            </div>
                        {% endfor %}
                        <div class="row">
                            <div class="col-xl-12">
                                <div class="slider_text ">
                                    <span>the best medical center</span>
                                    <h3> <span>Bringing health</span> <br> to life for the whole family.</h3>
                                    {% comment %}
                                        <a href="{% url 'account_login' %}" class="boxed-btn5">Discover More</a>
                                    {% endcomment %}
                                    {% if user.role.name == "Patient" %}
                                        <a class="popup-with-form boxed-btn5" href="#test-form" >Book  Appointment</a>
                                    {% else %}
                                    {% endif%}
                                    <form id="test-form" class="white-popup-block mfp-hide" class="booking" method="post" action="{% url 'booking' %}" >
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script>
            $('.popup-with-form').on('click',function(){
                var doctorId = $(this).data('value');
                console.log("aa", doctorId);
                $.ajax({
                    type:"GET",
                    url: "../../appointments/booking/",
                    data: { 'doctor_id': doctorId },
                    success: function( data )
                    {
                        $('#test-form').html(data)
                        $('#id_doctor').select2();
                    }
                })
            });
        </script>
    {% endblock %}

    <!-- JS here -->
    <script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/ajax-form.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'js/scrollIt.js' %}"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/gijgo.min.js' %}"></script>
    <!--contact js-->
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>

</body>

</html>

templates/specialities.html
{% extends 'index.html' %}
{% load static   %}
{% block content %}
<div class="depertment_area">
    <div class="container">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            {% for spec in specialities %}
                <li class="nav-item">
                <a class="nav-link {% if forloop.counter == 1%}active{%else%}{%endif%}" id="{{spec.specialities}}-tab" data-toggle="tab" href="#{{spec.specialities}}" role="tab" aria-controls="{{spec.specialities}}" aria-selected="true">
                    <h4>{{spec.specialities__name}}</h4>
                    ({{spec.specialities__count}})
                </a>
                </li>
            {% endfor %}
        </ul>
        <div class="tab-content" id="myTabContent">
            {% for spec in specialities %}
                <div class="tab-pane fade  {% if forloop.counter == 1%}show active{%else%}{%endif%}" id="{{spec.specialities}}" role="tabpanel" aria-labelledby="{{spec.specialities}}-tab">
                    {% for d in doctors %}
                        {% if d.specialities.name == spec.specialities__name %}
                            <div class="row justify-content-center">
                                <div class="col-lg-4 col-md-6">
                                    <div class="single_expert">
                                        <div class="expert_thumb">
                                            <img src="{{d.photo.url}}">
                                        </div>
                                        <div class="experts_name text-center">
                                            <h3>{{d.first_name}} {{d.last_name}}</h3>
                                            {{d.contact}}
                                            <span>{{d.specialities__name}}</span>
                                        </div>
                                        <div class="book_room">
                                            <div class="book_btn">
                                                {% if user.role.name == "Patient" %}
                                                <a class="popup-with-form" href="#test-form" data-value={{d.id}}>Book  Appointment</a>
                                            {% else %}
                                            {% endif%} 
                                           
                                            
                                            <form id="test-form" class="white-popup-block mfp-hide" class="booking" method="post" action="{% url 'booking' %}">
                                            </form>
                                        </div>
                                        </div>
                                     
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}  
                </div>
            {% endfor %}
        </div>
    </div>
</div>
<script>
    $('.popup-with-form').on('click',function(){
        var doctorId = $(this).data('value');
        $.ajax(
            {   
                type:"GET",
                url: "../../appointments/booking/",
                data: { 'doctor_id': doctorId },
                success: function( data ) 
                {
                    $('#test-form').html(data)
                    $('#id_doctor').select2();
                }
        })
    });
</script>

{% endblock %}